config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  root 'posts#index'

  resources :posts do
    member do
      get 'graph'
    end
  end
  resources :items

end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :spirit, presence: true
  validates :technique, presence: true
  validates :body, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @spirit = Post.all.sum(:spirit).to_i
    @technique = Post.all.sum(:technique).to_i
    @body = Post.all.sum(:body).to_i
    @sum = @spirit + @technique + @body
    @user = current_user.id
  end

  def create
    @items = Item.new(item_params)
    if @items.save
      redirect_to action: :index
    else
      render :new
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :explanation, :status, :count).merge(user_id: current_user.id)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show]
  before_action :move_to_index, except: [:index]

  def index 
    @posts = Post.all.order(created_at: 'desc').limit(4)
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to action: :index
    else
      render :edit
    end
  end

  def graph
    @spirit = Post.all.sum(:spirit).to_i
    @technique = Post.all.sum(:technique).to_i
    @body = Post.all.sum(:body).to_i
    @sum = @spirit + @technique + @body
    @user = current_user
  end

  private

  def post_params
    params.require(:post).permit(:spirit, :technique, :body).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.haml
.itemShop
  .itemShop__header
    .itemShop__header__title
      アイテムショップ
  .itemShop__main
    .itemShop__main__title
      アイテムを選択してください
    .itemShop__main__lists
      .itemShop__main__lists-1
        .itemShop__main__lists__leftBox
          .itemShop__main__lists__leftBox__image
            = image_tag 'ticket1.png', alt: '画像', class: 'itemImage'
        .itemShop__main__lists__rightBox
        = form_with model: Item.new do |f| 
          .itemShop__main__lists__rightBox__name
            1000円券
            = f.hidden_field :name, :value => "1000円券"
          .itemShop__main__lists__rightBox__explanation
            1000円までなら自由に使ってよい
            = f.hidden_field :explanation, :value => "1000円までなら自由に使ってよい"
          .itemShop__main__lists__rightBox__text
            .itemShop__main__lists__rightBox__text__price
              100ポイント
              = f.hidden_field :price, :value => "100"
            .itemShop__main__lists__rightBox__text__btn
              = f.hidden_field :status, :value => "1"
              = f.hidden_field :count, :value => "1"
              -if @sum >= 100
                = f.submit "購入", class: "submit"
              -else
                %p 100ポイント貯めて！

      .itemShop__main__lists-2
        .itemShop__main__lists__leftBox
          .itemShop__main__lists__leftBox__image
            = image_tag 'ticket2.png', alt: '画像', class: 'itemImage'
        .itemShop__main__lists__rightBox
        = form_with model: Item.new do |f| 
          .itemShop__main__lists__rightBox__name
            2000円券
            = f.hidden_field :name, :value => "2000円券"
          .itemShop__main__lists__rightBox__explanation
            2000円までなら自由に使ってよい
            = f.hidden_field :explanation, :value => "2000円までなら自由に使ってよい"
          .itemShop__main__lists__rightBox__text
            .itemShop__main__lists__rightBox__text__price
              200ポイント
              = f.hidden_field :price, :value => "200"
            .itemShop__main__lists__rightBox__text__btn
              = f.hidden_field :status, :value => "1"
              = f.hidden_field :count, :value => "1"
              -if @sum >= 200
                = f.submit "購入", class: "submit"
              -else
                %p 200ポイント貯めて！

      .itemShop__main__lists-3
        .itemShop__main__lists__leftBox
          .itemShop__main__lists__leftBox__image
            = image_tag 'ticket3.png', alt: '画像', class: 'itemImage'
        .itemShop__main__lists__rightBox
        = form_with model: Item.new do |f| 
          .itemShop__main__lists__rightBox__name
            3000円券
            = f.hidden_field :name, :value => "3000円券"
          .itemShop__main__lists__rightBox__explanation
            3000円までなら自由に使ってよい
            = f.hidden_field :explanation, :value => "3000円までなら自由に使ってよい"
          .itemShop__main__lists__rightBox__text
            .itemShop__main__lists__rightBox__text__price
              300ポイント
              = f.hidden_field :price, :value => "300"
            .itemShop__main__lists__rightBox__text__btn
              = f.hidden_field :status, :value => "1"
              = f.hidden_field :count, :value => "1"
              -if @sum >= 300
                = f.submit "購入", class: "submit"
              -else
                %p 300ポイント貯めて！

      .itemShop__main__lists-4
        .itemShop__main__lists__leftBox
          .itemShop__main__lists__leftBox__image
            = image_tag 'ticket.png', alt: '画像', class: 'itemImage'
        .itemShop__main__lists__rightBox
          .itemShop__main__lists__rightBox__name
            アイテム名
          .itemShop__main__lists__rightBox__explanation
            アイテム説明
          .itemShop__main__lists__rightBox__text
            .itemShop__main__lists__rightBox__text__price
              ポイント
            .itemShop__main__lists__rightBox__text__btn
 
      .itemShop__main__lists__footer
        .itemShop__main__lists__footer__left
          .itemShop__main__lists__footer__left__btn
            = link_to "トップページ", posts_path, class: 'btn'
        .itemShop__main__lists__footer__right
          .itemShop__main__lists__footer__right__btn
            = link_to "マイページ", graph_post_path(@user), class: 'btn'
  .itemShop__footer

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/posts/edit.html.haml
.wrapper
  .header
    努力可視化メーター
  .main
    .mainText
      .mainText__title
        成果を入力して下さい
        .mainText__title__content
          心：家事など,技：勉強など,体：運動など（整数のみ）
      .mainText__list
        = form_with(model: @post, local: true) do |f| 
          .mainText__list__1
            心
            = f.number_field :spirit, min: 0, max: 10, class: "spirit"
            時間
          .mainText__list__2
            技
            = f.number_field :technique, min: 0, max: 10, class: "technique"
            時間
          .mainText__list__3
            体
            = f.number_field :body, min: 0, max: 10, class: "body"
            時間
          .mainText__list__4
            = f.submit "訂正", class: "submit"

app/views/posts/graph.html.erb
<div class="header">
  マイページ
</div>
    
<div class="main">
  <div class="mainTop">
    <div class="userImage">
      <img src='user_image.png' alt='画像' height="300" width="300">
    </div>
    <div class="userInfo">
      <div class="userInfo_1">
        ユーザー名： <%= @user.nickname %>
      </div>
      <div class="userInfo_2">
        努力ポイント： <%= @sum %>ポイント
      </div>
      <div class="userInfo_3">
        <div class="button1">
          <a href="/items">アイテムショップ</a>
        </div>
        <div class="button2">
          <a href="/">トップページ</a>
        </div>
      </div>
    </div>
  </div>
  <div class="mainBottom">
    <div style="position:absolute; top:420px; width:500px; height:280px;">
      <canvas id="myChart"></canvas>
    </div>
      <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: ["心","技","体"],
        datasets: [{
          label: '積み上げ',
          data: [
            <%= Post.all.sum(:spirit) %>,
            <%= Post.all.sum(:technique) %>,
            <%= Post.all.sum(:body) %>
            ],
          backgroundColor: [
              'rgba(255, 99, 132, 0.2)',
              'rgba(54, 162, 235, 0.2)',
              'rgba(255, 206, 86, 0.2)'
          ],
          borderColor: [
              'rgba(255,99,132,1)',
              'rgba(54, 162, 235, 1)',
              'rgba(255, 206, 86, 1)'
          ],
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero:true
            }
          }]
        }
      }
      });
      </script>
  </div>
</div>

app/views/posts/index.html.haml
.wrapper
  .header
    努力可視化メーター
  .content
    .contentUser
      = image_tag 'user_image.png', alt: '画像', class: 'userImage'
    .contentIcon
      %details
        %summary= icon("fas", "cogs")
        -if user_signed_in?
          .user_nav
          = link_to "マイページ", graph_post_path(current_user.id), class: "contentShow", method: :get
          %br= link_to "ログアウト", destroy_user_session_path, class: "contentShow", method: :delete
        -else
          .grid-6
          = link_to "ログイン", new_user_session_path, class: "contentShow"
          %br= link_to "新規登録", new_user_registration_path, class: "contentShow"
  .main
    .mainTitle
      %h2
      積み上げ結果
      .mainText
        .mainText__left
          
          = image_tag 'user_image.png', alt: '画像', class: 'userImage'
        .mainText__right
          .textTittle
            .textTittle__box
              = link_to "新規成果入力", new_post_path, class: "textTittle__content"
          .textContent
            - @posts.each do |post|
              .balloonLeft
                = post.created_at.strftime('%Y/%m/%d')
                心が 
                = post.spirit
                ポイント上がった！
                技が
                = post.technique
                ポイント上がった！
                体が
                = post.body
                ポイント上がった！
                = link_to '編集', edit_post_path(post.id), class: "contentEdit", method: :get
                = link_to '削除', post_path(post.id), class: "contentDelete", method: :delete

app/views/posts/index3.html.haml
.Wrapper
  .Header
    可視化メーター
  .Content
    %details
      %summary= icon("fas", "cogs")
      = link_to "パラメーター", "/posts/new"
      = link_to "ログアウト"
  .Main
    .Main__title
      %h2
      積み上げ結果
    .Main__text
      .textContent
      
        - @posts.each do |post|
          %p
            心が 
            = link_to post.spirit, post_path(post.id) 
            ポイント上がった！
            
            技が
            = link_to post.technique, post_path(post.id)
            ポイント上がった！
            体が
            = link_to post.body, post_path(post.id)
            ポイント上がった！
            = link_to '編集', edit_post_path(post.id)


      

app/views/posts/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
  <script src="Chart.min.js"></script>
</head>
<body>
  <canvas id="ch"></canvas>
<script>
var ctx = document.getElementById("ch").getContext("2d");
var chart = new Chart(ctx, {
  type: "horizontalBar",
  data:{
    labels:["心","技","体"],
    datasets:[{
      data:[4,5,9,14,15,24,30]
    }]
  },
  options:{}
});
</script>
</body>
</html>

<%= @post %>
<%= @i %>



<%= link_to "トップページ", "/" %>

app/views/posts/new.html.haml
.wrapper
  .header
    努力可視化メーター
  .main
    .mainText
      .mainText__title
        成果を入力して下さい
        .mainText__title__content
          心：家事など,技：勉強など,体：運動など（整数のみ）
      .mainText__list
        = form_with model: Post.new do |f| 
          .mainText__list__1
            心
            = f.number_field :spirit, min: 0, max: 10, class: "spirit"
            時間
          .mainText__list__2
            技
            = f.number_field :technique, min: 0, max: 10, class: "technique"
            時間
          .mainText__list__3
            体
            = f.number_field :body, min: 0, max: 10, class: "body"
            時間
          .mainText__list__4
            = f.submit "送信", class: "submit"